# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tender Is The Byte
description: >- # this means to ignore newlines the next tag
  Hi!  I'm Ryan Moore, NBA fan & PhD candidate in Eric Wommack's viral ecology lab @ UD.
url: https://www.TenderIsTheByte.com # the base hostname & protocol for your site, e.g. http://example.com
author:
  twitter: TenderIsTheByte
  github: mooreryan
  name: Ryan Moore
  email: moorer@udel.edu
twitter:
  username: TenderIsTheByte
  card: summary
logo: assets/img/favicon/favicon-196x196.png
social:
  name: Ryan Moore
  links:
    - https://twitter.com/TenderIsTheByte
    - https://github.com/mooreryan

copyright: © Ryan Moore, 2019
baseurl: "" # the subpath of your site, e.g. /blog

# Treat images as if they had image: true in the front matter
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true


# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
markdown: kramdown



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
  - build_exclude
  - README.md
  - LICENSE.txt

# Pages to include in the nav bar
header_pages:
  - about.md
  - apps.md

# I want the sass partials in the assets folder so need to tell Jekyll about that.
sass:
  sass_dir: assets/_sass
  style: compressed

permalink: /:categories/:year/:month/:day/:title/

collections_dir: collections

collections:
  apps:
    output: true
    permalink: /:collection/:title

# Variables for folders and such
dir:
  post_img: /assets/img/posts
  apps: /apps

# List of apps
apps:
  - mgs_bias